---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ckan-version: [2.9, 2.9-py2, 2.8]

    name: Continuous Integration build on CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container: integratedexperts/ci-builder
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build
        run: .circleci/build.sh
        timeout-minutes: 15

      - name: Test lint
        run: .circleci/test-lint.sh
        timeout-minutes: 30

      - name: Test
        run: .circleci/test.sh
        timeout-minutes: 30

      - name: Test BDD
        run: .circleci/test-bdd.sh
        timeout-minutes: 40

      - name: Retrieve logs
        if: always()
        run: .circleci/get-logs.sh
        timeout-minutes: 5

      - name: Retrieve screenshots
        if: always()
        run: .circleci/process-artifacts.sh
        timeout-minutes: 1

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: CKAN ${{ matrix.ckan-version }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
