---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 .

  test:
    strategy:
      fail-fast: true
      matrix:
        ckan-version: [2.9, 2.9-py2]
        behave-tag: [smoke, authenticated, unauthenticated]

    name: Continuous Integration build on CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container: drevops/ci-builder
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}
      BEHAVE_TAG: ${{ matrix.behave-tag }}

    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 2

      - name: Build
        run: .circleci/build.sh
        timeout-minutes: 15

      - name: Test lint
        run: .circleci/test-lint.sh
        timeout-minutes: 3

      - name: Test BDD
        run: .circleci/test-bdd.sh
        timeout-minutes: 45

      - name: Test
        run: .circleci/test.sh
        timeout-minutes: 45

      - name: Retrieve logs
        if: always()
        run: .circleci/get-logs.sh
        timeout-minutes: 5

      - name: Retrieve screenshots
        if: always()
        run: .circleci/process-artifacts.sh
        timeout-minutes: 1

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: CKAN ${{ matrix.ckan-version }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
